// Dish knowledge is transcribed verbatim from the supplied development script.
export const DISHES = [
  {
    "id": "01",
    "name": "白切鸡",
    "cuisine": "粤菜",
    "province": "广东",
    "chapter": 1,
    "knowledge": "白切鸡是广东常见的特色菜，名称也写作“白斩鸡”。",
    "recognition": "浅色鸡块与小蘸碟",
    "image": "art/dishes-v1/icons-256/01-baiqieji.png",
    "large": "art/dishes-v1/sprites-1024/01-baiqieji.png"
  },
  {
    "id": "02",
    "name": "虾饺",
    "cuisine": "粤菜",
    "province": "广东",
    "chapter": 1,
    "knowledge": "以鲜虾为主要馅料，外皮晶莹透亮，口感鲜嫩爽滑，是经典粤式点心",
    "recognition": "半透明褶边饺形",
    "image": "art/dishes-v1/icons-256/02-xiajiao.png",
    "large": "art/dishes-v1/sprites-1024/02-xiajiao.png"
  },
  {
    "id": "03",
    "name": "肠粉",
    "cuisine": "粤菜",
    "province": "广东",
    "chapter": 1,
    "knowledge": "用米浆蒸成薄嫩粉皮，包裹虾仁、牛肉等馅料，再淋上酱油，口感柔滑鲜香。",
    "recognition": "白色米皮卷与酱汁",
    "image": "art/dishes-v1/icons-256/03-changfen.png",
    "large": "art/dishes-v1/sprites-1024/03-changfen.png"
  },
  {
    "id": "04",
    "name": "叉烧包",
    "cuisine": "粤菜",
    "province": "广东",
    "chapter": 1,
    "knowledge": "以松软面皮包裹甜咸适中的叉烧馅，口感蓬松香甜，是广式早茶代表点心之一。",
    "recognition": "圆包与裂口红褐馅",
    "image": "art/dishes-v1/icons-256/04-chashaobao.png",
    "large": "art/dishes-v1/sprites-1024/04-chashaobao.png"
  },
  {
    "id": "05",
    "name": "烧卖",
    "cuisine": "粤菜",
    "province": "广东",
    "chapter": 1,
    "knowledge": "以薄面皮包裹猪肉、虾仁等馅料蒸制而成，顶部开口，口感鲜香饱满。",
    "recognition": "黄色开口点心",
    "image": "art/dishes-v1/icons-256/05-shaomai.png",
    "large": "art/dishes-v1/sprites-1024/05-shaomai.png"
  },
  {
    "id": "06",
    "name": "麻婆豆腐",
    "cuisine": "川菜",
    "province": "四川",
    "chapter": 2,
    "knowledge": "以嫩豆腐配牛肉末或猪肉末烹制，突出麻、辣、鲜、香、烫等特点，是川菜代表名菜。",
    "recognition": "红色汤汁与白豆腐块",
    "image": "art/dishes-v1/icons-256/06-mapodoufu.png",
    "large": "art/dishes-v1/sprites-1024/06-mapodoufu.png"
  },
  {
    "id": "07",
    "name": "回锅肉",
    "cuisine": "川菜",
    "province": "四川",
    "chapter": 2,
    "knowledge": "将煮熟的猪肉切片回锅爆炒，配以豆瓣酱、蒜苗等调味，香辣浓郁、肥而不腻。",
    "recognition": "肉片与绿叶配菜",
    "image": "art/dishes-v1/icons-256/07-huiguorou.png",
    "large": "art/dishes-v1/sprites-1024/07-huiguorou.png"
  },
  {
    "id": "08",
    "name": "开水白菜",
    "cuisine": "川菜",
    "province": "四川",
    "chapter": 2,
    "knowledge": "以白菜心配高级清汤烹制，看似清淡如水，实则汤味醇厚鲜美，体现川菜精细雅致的一面。",
    "recognition": "浅色汤与整束白菜心",
    "image": "art/dishes-v1/icons-256/08-kaishuibaicai.png",
    "large": "art/dishes-v1/sprites-1024/08-kaishuibaicai.png"
  },
  {
    "id": "09",
    "name": "樟茶鸭",
    "cuisine": "川菜",
    "province": "四川",
    "chapter": 2,
    "knowledge": "鸭肉经腌制、熏制和蒸炸等工序制成，带有独特的樟木与茶叶熏香，外酥里嫩。",
    "recognition": "深色鸭块；与白切鸡明显区分",
    "image": "art/dishes-v1/icons-256/09-zhangchaya.png",
    "large": "art/dishes-v1/sprites-1024/09-zhangchaya.png"
  },
  {
    "id": "10",
    "name": "四川什锦泡菜",
    "cuisine": "川菜",
    "province": "四川",
    "chapter": 2,
    "knowledge": "将多种蔬菜放入泡菜坛中发酵而成，口感酸爽脆嫩，是四川家庭常见的佐餐小菜。",
    "recognition": "多色蔬菜条与小泡菜坛",
    "image": "art/dishes-v1/icons-256/10-sichuan-shijin-paocai.png",
    "large": "art/dishes-v1/sprites-1024/10-sichuan-shijin-paocai.png"
  },
  {
    "id": "11",
    "name": "糖醋鲤鱼",
    "cuisine": "鲁菜",
    "province": "山东",
    "chapter": 3,
    "knowledge": "以整条鲤鱼炸制后浇上糖醋汁，色泽红亮，外酥里嫩，酸甜鲜香。",
    "recognition": "整鱼拱形与亮色酱汁",
    "image": "art/dishes-v1/icons-256/11-tangcu-liyu.png",
    "large": "art/dishes-v1/sprites-1024/11-tangcu-liyu.png"
  },
  {
    "id": "12",
    "name": "葱烧海参",
    "cuisine": "鲁菜",
    "province": "山东",
    "chapter": 3,
    "knowledge": "以海参和大葱为主料烧制，突出葱香浓郁、海参软糯鲜美，是鲁菜代表性海味菜肴。",
    "recognition": "深色海参和长葱段",
    "image": "art/dishes-v1/icons-256/12-congshao-haishen.png",
    "large": "art/dishes-v1/sprites-1024/12-congshao-haishen.png"
  },
  {
    "id": "13",
    "name": "奶汤蒲菜",
    "cuisine": "鲁菜",
    "province": "山东",
    "chapter": 3,
    "knowledge": "以蒲菜配浓醇奶汤烹制，汤色乳白、口味鲜醇。",
    "recognition": "乳白汤与浅色蒲菜段",
    "image": "art/dishes-v1/icons-256/13-naitang-pucai.png",
    "large": "art/dishes-v1/sprites-1024/13-naitang-pucai.png"
  },
  {
    "id": "14",
    "name": "油爆双脆",
    "cuisine": "鲁菜",
    "province": "山东",
    "chapter": 3,
    "knowledge": "通常以猪肚尖和鸡胗等脆嫩食材快速爆炒，讲究火候迅疾、口感爽脆。",
    "recognition": "浅色小块与宽口盘",
    "image": "art/dishes-v1/icons-256/14-youbao-shuangcui.png",
    "large": "art/dishes-v1/sprites-1024/14-youbao-shuangcui.png"
  },
  {
    "id": "15",
    "name": "德州扒鸡",
    "cuisine": "鲁菜",
    "province": "山东",
    "chapter": 3,
    "knowledge": "整鸡经炸制、卤煮等工序制成，色泽红润、肉质酥烂、香味浓郁。",
    "recognition": "完整棕色鸡形",
    "image": "art/dishes-v1/icons-256/15-dezhou-paji.png",
    "large": "art/dishes-v1/sprites-1024/15-dezhou-paji.png"
  },
  {
    "id": "16",
    "name": "松鼠鳜鱼",
    "cuisine": "苏菜",
    "province": "江苏",
    "chapter": 4,
    "knowledge": "将鳜鱼改刀炸至外形似松鼠，再浇上酸甜卤汁，外酥里嫩、酸甜鲜香",
    "recognition": "展开的鱼肉与颗粒刀花",
    "image": "art/dishes-v1/icons-256/16-songshu-guiyu.png",
    "large": "art/dishes-v1/sprites-1024/16-songshu-guiyu.png"
  },
  {
    "id": "17",
    "name": "清炖狮子头",
    "cuisine": "苏菜",
    "province": "江苏",
    "chapter": 4,
    "knowledge": "以肥瘦相间的猪肉制成大肉丸慢火清炖，口感松软鲜嫩、汤味醇厚。",
    "recognition": "大圆肉丸与浅汤",
    "image": "art/dishes-v1/icons-256/17-qingdun-shizitou.png",
    "large": "art/dishes-v1/sprites-1024/17-qingdun-shizitou.png"
  },
  {
    "id": "18",
    "name": "文思豆腐",
    "cuisine": "苏菜",
    "province": "江苏",
    "chapter": 4,
    "knowledge": "将嫩豆腐切成细如发丝的豆腐丝入汤烹制，刀工精细、口感清鲜，体现精湛的刀工技艺。",
    "recognition": "碗中细白丝；区别豆腐块",
    "image": "art/dishes-v1/icons-256/18-wensi-doufu.png",
    "large": "art/dishes-v1/sprites-1024/18-wensi-doufu.png"
  },
  {
    "id": "19",
    "name": "金陵盐水鸭",
    "cuisine": "苏菜",
    "province": "江苏",
    "chapter": 4,
    "knowledge": "以鸭肉经盐腌、复卤等工序制成，皮白肉嫩、咸鲜清香，是南京传统名菜。",
    "recognition": "浅色鸭片；配菜牌突出名称",
    "image": "art/dishes-v1/icons-256/19-jinling-yanshuiya.png",
    "large": "art/dishes-v1/sprites-1024/19-jinling-yanshuiya.png"
  },
  {
    "id": "20",
    "name": "扬州炒饭",
    "cuisine": "苏菜",
    "province": "江苏",
    "chapter": 4,
    "knowledge": "以米饭配鸡蛋、虾仁、火腿等多种食材炒制，色彩丰富、颗粒分明、鲜香可口。",
    "recognition": "彩色配料与散开的饭粒",
    "image": "art/dishes-v1/icons-256/20-yangzhou-chaofan.png",
    "large": "art/dishes-v1/sprites-1024/20-yangzhou-chaofan.png"
  },
  {
    "id": "21",
    "name": "龙井虾仁",
    "cuisine": "浙菜",
    "province": "浙江",
    "chapter": 5,
    "knowledge": "以鲜虾仁配龙井茶叶炒制，色泽清雅、虾仁鲜嫩，并带有淡淡茶香。",
    "recognition": "白色虾仁与少量茶叶",
    "image": "art/dishes-v1/icons-256/21-longjing-xiaren.png",
    "large": "art/dishes-v1/sprites-1024/21-longjing-xiaren.png"
  },
  {
    "id": "22",
    "name": "西湖醋鱼",
    "cuisine": "浙菜",
    "province": "浙江",
    "chapter": 5,
    "knowledge": "以鲜鱼烹制后浇上糖醋芡汁，鱼肉细嫩，酸甜适口。",
    "recognition": "平放整鱼与褐色酱汁",
    "image": "art/dishes-v1/icons-256/22-xihu-cuyu.png",
    "large": "art/dishes-v1/sprites-1024/22-xihu-cuyu.png"
  },
  {
    "id": "23",
    "name": "东坡肉",
    "cuisine": "浙菜",
    "province": "浙江",
    "chapter": 5,
    "knowledge": "以五花肉加酱油、黄酒等慢火焖制，色泽红亮、酥烂醇香、肥而不腻。",
    "recognition": "方形肉块与小碗",
    "image": "art/dishes-v1/icons-256/23-dongporou.png",
    "large": "art/dishes-v1/sprites-1024/23-dongporou.png"
  },
  {
    "id": "24",
    "name": "油焖春笋",
    "cuisine": "浙菜",
    "province": "浙江",
    "chapter": 5,
    "knowledge": "以鲜嫩春笋加油和酱汁焖制，口感脆嫩鲜甜，突出江南春季时令风味。",
    "recognition": "棕黄色笋段",
    "image": "art/dishes-v1/icons-256/24-youmen-chunsun.png",
    "large": "art/dishes-v1/sprites-1024/24-youmen-chunsun.png"
  },
  {
    "id": "25",
    "name": "西湖莼菜汤",
    "cuisine": "浙菜",
    "province": "浙江",
    "chapter": 5,
    "knowledge": "以西湖莼菜配高汤烹制，口感滑嫩清鲜，是富有杭州地方特色的传统汤菜。",
    "recognition": "清汤与小片绿色莼菜",
    "image": "art/dishes-v1/icons-256/25-xihu-chuncaitang.png",
    "large": "art/dishes-v1/sprites-1024/25-xihu-chuncaitang.png"
  },
  {
    "id": "26",
    "name": "米饭",
    "cuisine": "共用",
    "province": "",
    "chapter": 0,
    "knowledge": "米饭由大米加水蒸煮而成，是日常餐桌上的常见主食。",
    "recognition": "小碗中隆起的纯白米饭；没有彩色配料",
    "image": "art/dishes-v1/icons-256/26-mifan.png",
    "large": "art/dishes-v1/sprites-1024/26-mifan.png"
  },
  {
    "id": "27",
    "name": "清炒青菜",
    "cuisine": "共用",
    "province": "",
    "chapter": 0,
    "knowledge": "清炒青菜以绿叶蔬菜快速炒制，保留鲜绿的色泽与清爽的口感。",
    "recognition": "盘中饱满的绿色菜叶与浅绿菜梗；没有汤底",
    "image": "art/dishes-v1/icons-256/27-qingchao-qingcai.png",
    "large": "art/dishes-v1/sprites-1024/27-qingchao-qingcai.png"
  },
  {
    "id": "28",
    "name": "蒸蛋",
    "cuisine": "共用",
    "province": "",
    "chapter": 0,
    "knowledge": "蒸蛋以鸡蛋加水调匀后蒸制，成品细嫩柔滑。",
    "recognition": "小碗中平滑完整的淡黄色蛋羹表面",
    "image": "art/dishes-v1/icons-256/28-zhengdan.png",
    "large": "art/dishes-v1/sprites-1024/28-zhengdan.png"
  },
  {
    "id": "29",
    "name": "萝卜汤",
    "cuisine": "共用",
    "province": "",
    "chapter": 0,
    "knowledge": "萝卜汤以萝卜加水或高汤煮制，是常见的家常汤品。",
    "recognition": "清汤中清晰可见的大块白萝卜；区别细白丝与蒲菜段",
    "image": "art/dishes-v1/icons-256/29-luobotang.png",
    "large": "art/dishes-v1/sprites-1024/29-luobotang.png"
  }
];

export const dishById = Object.fromEntries(DISHES.map((dish) => [dish.id, dish]));

export const CHAPTERS = [
  {
    id: 1,
    name: '粤菜开张',
    cuisine: '粤菜',
    province: '广东',
    short: '岭南',
    badge: '岭南食谱章',
    description: '从三道菜到四道菜，记住菜单原来的顺序，迎接食谱铺的第一桌客人。',
    knowledge: '粤菜发源于岭南地区，讲究食材鲜活、口味清鲜，擅长蒸、炖、烧、煲等技法，尤以海鲜、烧味和广式点心闻名。',
    color: '#627654',
    decor: {
      id: 'panda-carving',
      name: '熊猫木雕',
      description: '一只衔着绿叶的熊猫木雕，静静守候岭南的第一缕茶香。',
    },
    quiz: {
      question: '把“粤菜”名签放到对应的省份。',
      options: ['广东', '山东'],
      answer: 0,
      explanation: '粤菜对应广东，广州早茶有许多广式点心。',
    },
  },
  {
    id: 2,
    name: '川菜迎客',
    cuisine: '川菜',
    province: '四川',
    short: '西南',
    badge: '西南食谱章',
    description: '四道菜的订单会换掉一道，记住最新要求，再依次出餐。',
    knowledge: '川菜发源于四川地区，川菜以麻辣鲜香、味型丰富著称，善用辣椒、花椒和豆瓣酱等调味。',
    color: '#AD6048',
    decor: {
      id: 'red-lantern',
      name: '红绳灯笼',
      description: '暖红灯笼系着小小绳结，把热闹的迎客心意挂在屋檐下。',
    },
    quiz: {
      question: '哪道菜也在川菜经典名菜中？',
      options: ['开水白菜', '西湖醋鱼'],
      answer: 0,
      explanation: '本章不只有麻婆豆腐，开水白菜也是川菜名菜。',
    },
  },
  {
    id: 3,
    name: '鲁菜上桌',
    cuisine: '鲁菜',
    province: '山东',
    short: '齐鲁',
    badge: '齐鲁食谱章',
    description: '学会取消与加菜，留意其余菜品随之改变的位置。',
    knowledge: '鲁菜发源于山东地区，以咸鲜醇厚、突出本味著称，讲究火候与制汤，擅长爆、炒、烧、扒等烹调技法。',
    color: '#61788D',
    decor: {
      id: 'blue-fish',
      name: '青鱼挂饰',
      description: '青瓷小鱼随风轻摇，为食谱铺捎来齐鲁山海的清朗气息。',
    },
    quiz: {
      question: '哪张菜卡属于本章鲁菜？',
      options: ['葱烧海参', '虾饺'],
      answer: 0,
      explanation: '鲁菜对应山东，本章收集了5道代表菜。',
    },
  },
  {
    id: 4,
    name: '苏菜雅宴',
    cuisine: '苏菜',
    province: '江苏',
    short: '江淮',
    badge: '江淮食谱章',
    description: '从五道菜开始，经历短暂等待或连续换菜，以最后一条要求为准。',
    knowledge: '苏菜发源于江苏地区，讲究选料精细、刀工考究和原汁原味，口味清鲜平和，尤擅炖、焖、蒸、煨等烹调技法。',
    color: '#568A82',
    decor: {
      id: 'lotus-pot',
      name: '荷叶盆栽',
      description: '一方小盆盛着圆圆荷叶，让江淮水乡的绿意停在窗边。',
    },
    quiz: {
      question: '哪张菜卡属于本章苏菜？',
      options: ['奶汤蒲菜', '文思豆腐'],
      answer: 1,
      explanation: '苏菜对应江苏，本章收集了5道代表菜。',
    },
  },
  {
    id: 5,
    name: '浙菜收官',
    cuisine: '浙菜',
    province: '浙江',
    short: '吴越',
    badge: '吴越食谱章',
    description: '记住六道菜，逐条完成组合换单，为山海宴备齐最后一席。',
    knowledge: '浙菜发源于浙江地区，以清鲜爽嫩、注重本味著称，讲究时令食材与精细烹调，尤以杭州、宁波、绍兴等地方风味最具代表性。',
    color: '#B38A43',
    decor: {
      id: 'shanhai-sign',
      name: '山海匾额',
      description: '写着“山海食谱铺”的木匾，纪念五地风味汇成的一桌团圆宴。',
    },
    quiz: {
      question: '把五张菜系签配到省份签，一次配一组。',
      options: ['广东', '四川', '山东', '江苏', '浙江'],
      answer: 0,
      pairs: [
        { cuisine: '粤菜', province: '广东' },
        { cuisine: '川菜', province: '四川' },
        { cuisine: '鲁菜', province: '山东' },
        { cuisine: '苏菜', province: '江苏' },
        { cuisine: '浙菜', province: '浙江' },
      ],
      explanation: '粤菜对应广东，川菜对应四川，鲁菜对应山东，苏菜对应江苏，浙菜对应浙江。',
    },
  },
];

export const SOURCE = '《03_山海食谱铺_网游开发脚本》· 第六部分“中国菜系知识”；菜系对应关系参考国家移民管理局（2022）《欢迎来到中国》。';
export const source = SOURCE;